# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Nexys-A7-100T-Master.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_demo_0_0/top_demo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_demo_0_0 || ORIG_REF_NAME==top_demo_0_0} -quiet] -quiet

# IP: bd/top/ip/top_clk_div_0_0/top_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_clk_div_0_0 || ORIG_REF_NAME==top_clk_div_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_0_0/top_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_util_vector_logic_0_0 || ORIG_REF_NAME==top_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/top/top_ooc.xdc
